"""Initial migration

Revision ID: ac75ea5ef42f
Revises: 
Create Date: 2025-06-01 15:24:09.051678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ac75ea5ef42f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("voice_profiles", sa.Column("is_cloned", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("voice_profiles", "is_cloned")
    # ### end Alembic commands ###
